### ISSUE TITLE
ios系统 10.3 的 jz_navigationBarBackgroundHidden 设置为yes，导航栏分割线依然显示

### ISSUE THREAD

**Issue by souls-shaohui** [JazysYu/JZNavigationExtension#87]
测试了10.3和10.3.3的系统，都会显示分割线

**Comment by JazysYu** [comment]
iOS10以后导航栏的shadowImageView被移出了以前的backgroundView层级。[navigationBar setShadowImage:[UIImage new] ...] 用这个隐藏

**Comment by JazysYu** [comment]
#65

**Comment by zhouzhuhao** [comment]
通过[navigationBar setShadowImage:[UIImage new] ]移除分割线，就是你有设置导航栏的背景图片，不然也是没有用的，
官方API有说明：/* Default is nil. When non-nil, a custom shadow image to show instead of the default shadow image. For a custom shadow to be shown, a custom background image must also be set with -setBackgroundImage:forBarMetrics: (if the default background image is used, the default shadow image will be used).
 */
@property(nullable, nonatomic,strong) UIImage *shadowImage NS_AVAILABLE_IOS(6_0) UI_APPEARANCE_SELECTOR;

**Comment by zhouzhuhao** [comment]
/* Default is nil. When non-nil, a custom shadow image to show instead of the default shadow image. For a custom shadow to be shown, a custom background image must also be set with -setBackgroundImage:forBarMetrics: (if the default background image is used, the default shadow image will be used).
 */
@property(nullable, nonatomic,strong) UIImage *shadowImage NS_AVAILABLE_IOS(6_0) UI_APPEARANCE_SELECTOR;

**Comment by JohnChaseK** [comment]
/* Default is nil. When non-nil, a custom shadow image to show instead of the default shadow image. For a custom shadow to be shown, a custom background image must also be set with -setBackgroundImage:forBarMetrics: (if the default background image is used, the default shadow image will be used).
 */
@property(nullable, nonatomic,strong) UIImage *shadowImage NS_AVAILABLE_IOS(6_0) UI_APPEARANCE_SELECTOR; 要想通过shadowImage去掉分割线，必须设置导航栏的背景图片
